# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-04 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='location',
            new_name='姓名',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='學號',
        ),
    ]
